export const StationsColumns = [
  {
    title: "Action",
    web1: "20px",
    web2: "text-[25px]",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "phone",
    title: "Station Number",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    title: "Company Name",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "name",
    title: "Station Name",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
  {
    id: "address",
    title: "Address",
    web1: "20px",
    web2: "25px",
    web3: "30px",
    web4: "35px",
  },
];
