export const data = [
  {
    favourites: true,
    StationName: "ABC F",
    LastOrder: "10/Oct/23",
    HiOctane: true,
    HiOctaneCapacity: 3000,
    Octane: true,
    OctaneCapacity: 3000,
    Diesel: true,
    DieselCapacity: 3000,
    status: "BeReady",
    // BeReady: true,
    // Healthy: true,
    // MakeOrder: true,
  },
  {
    favourites: false,
    StationName: "ABC",
    LastOrder: "10/Oct/23",
    HiOctane: false,
    HiOctaneCapacity: 3000,
    Octane: true,
    OctaneCapacity: 3000,
    Diesel: false,
    DieselCapacity: 3000,
    status: "Healthy",
    // Healthy: true,
    // MakeOrder: true,
  },
  {
    favourites: true,
    StationName: "ABC F",
    LastOrder: "10/Oct/23",
    HiOctane: false,
    HiOctaneCapacity: 3000,
    Octane: true,
    OctaneCapacity: 3000,
    Diesel: false,
    DieselCapacity: 3000,
    status: "Healthy",
    // Healthy: true,
    // MakeOrder: true,
  },
  {
    favourites: false,
    StationName: "ABC",
    LastOrder: "10/Oct/23",
    HiOctane: false,
    HiOctaneCapacity: 3000,
    Octane: true,
    OctaneCapacity: 3000,
    Diesel: false,
    DieselCapacity: 3000,
    status: "Healthy",
    // Healthy: true,
    // MakeOrder: true,
  },
  {
    favourites: false,
    StationName: "ABC",
    LastOrder: "10/Oct/23",
    HiOctane: false,
    HiOctaneCapacity: 3000,
    Octane: true,
    OctaneCapacity: 3000,
    Diesel: true,
    DieselCapacity: 3000,
    status: "MakeOrder",
    // Healthy: true,
    // MakeOrder: true,
  },
  {
    favourites: false,
    StationName: "ABC",
    LastOrder: "10/Oct/23",
    HiOctane: false,
    HiOctaneCapacity: 3000,
    Octane: true,
    OctaneCapacity: 3000,
    Diesel: true,
    DieselCapacity: 3000,
    status: "MakeOrder",
    // Healthy: true,
    // MakeOrder: true,
  },
  {
    favourites: true,
    StationName: "ABC F",
    LastOrder: "10/Oct/23",
    HiOctane: true,
    HiOctaneCapacity: 3000,
    Octane: true,
    OctaneCapacity: 3000,
    Diesel: true,
    DieselCapacity: 3000,
    status: "MakeOrder",
    // Healthy: true,
    // MakeOrder: true,
  },
  {
    favourites: true,
    StationName: "ABC F",
    LastOrder: "10/Oct/23",
    HiOctane: true,
    HiOctaneCapacity: 3000,
    Octane: false,
    OctaneCapacity: 3000,
    Diesel: true,
    DieselCapacity: 3000,
    status: "MakeOrder",
    // Healthy: true,
    // MakeOrder: true,
  },
];
