export const UserData = [
  {
    Username: "User 123",
    Email: "123@gmail.com",
    AuthorityandPrivlages: "Lorem ipsum",
    PhoneNumber: "1234567890",
    Role: "Driver",
  },
  {
    Username: "User 123",
    Email: "123@gmail.com",
    AuthorityandPrivlages: "Lorem ipsum",
    PhoneNumber: "1234567890",
    Role: "Driver",
  },
  {
    Username: "Zain",
    Email: "123@gmail.com",
    AuthorityandPrivlages: "Lorem ipsum",
    PhoneNumber: "1234567890",
    Role: "Order Manager",
  },
  {
    Username: "User 123",
    Email: "123@gmail.com",
    AuthorityandPrivlages: "Lorem ipsum",
    PhoneNumber: "1234567890",
    Role: "Driver",
  },
  {
    Username: "User 456",
    Email: "123@gmail.com",
    AuthorityandPrivlages: "Lorem ipsum",
    PhoneNumber: "1234567890",
    Role: "Driver",
  },
  {
    Username: "User 123",
    Email: "123@gmail.com",
    AuthorityandPrivlages: "Lorem ipsum",
    PhoneNumber: "1234567890",
    Role: "Station Manager",
  },
  {
    Username: "User 123",
    Email: "123@gmail.com",
    AuthorityandPrivlages: "Lorem ipsum",
    PhoneNumber: "1234567890",
    Role: "Driver",
  },
  {
    Username: "User 123",
    Email: "123@gmail.com",
    AuthorityandPrivlages: "Lorem ipsum",
    PhoneNumber: "1234567890",
    Role: "Driver",
  },
];
